### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by tzmfreedom** [tzmfreedom/forceq#1]
* [ ] execute query and output to stdout
* [ ] input from stdin and execute insert
* [ ] input from stdin and execute update
* [ ] input from stdin and execute upsert
* [ ] input from stdin and execute delete
* [ ] input from stdin, execute anonymous and output to stdout
